version: '3.8'
services:
  wol:
    image: ghcr.io/cute-angelia/wol-fork:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data       # SQLite 数据持久化
    environment:
      - WOLHTTPPORT=8080
      - WOLDB=/data/computer.db
    restart: unless-stopped
